name: Test Postman Collection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Start Mock API and Run Tests
        run: |
          npm run tern-on-api &
          sleep 10 
          npm run test:api

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: output.html

      - name: Prepare deployment directory
        run: |
          mkdir -p testResults
          cp output.html testResults/

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: testResults
