name: Test Postman Collection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Start Mock API and Run Tests
        run: |
          npm run tern-on-api & 
          sleep 5 
          npm run test:api

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: output.html

      - name: Deploy to GitHub Pages
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout gh-pages
          git rm -rf .
          git add output.html
          git commit -m "Deploy newman report"
          git push origin gh-pages --force
